## Array shape manipulation

### Flattening a multi-dimensional array

In [2]:
import numpy as np

In [12]:
a1 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
a1

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

#### ravel() returns a view

In [49]:
a2 = a1.ravel()
a2

array([1, 3, 9, 7, 2, 4, 0, 8])

In [16]:
a2[2] = 9
a2[-2] = 0
a1

array([[1, 3, 9, 7],
       [2, 4, 0, 8]])

#### flatten() returns a copy

In [ ]:
a3 = a1.flatten()
a3

In [18]:
a3[4] = 100
a1

array([[1, 3, 9, 7],
       [2, 4, 0, 8]])

### Reshaping

#### numpy.ndarray.reshape and numpy.reshape return a view

In [ ]:
b1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b1

In [20]:
b2 = b1.reshape(3, 3)
b2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
b2[1, 2] = 0
b1

array([1, 2, 3, 4, 5, 0, 7, 8, 9])

In [51]:
b3 = np.reshape(b1, (3, 3))
b3

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

In [52]:
b3[2, 0] = 0
b1

array([1, 2, 3, 4, 5, 0, 0, 8, 9])

### Resizing

#### numpy.ndarray.resize resizes in-place

In [48]:
c1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
c1.resize(3, 5)
c1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 0, 0],
       [0, 0, 0, 0, 0]])

#### numpy.resize returns a new array

In [47]:
c2 = np.resize(c1, (4,3))
c2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0],
       [0, 0, 0]])

### Adding a dimension

In [38]:
d1 = np.array([1, 2, 3, 4])
d1

array([1, 2, 3, 4])

In [39]:
d2 = d1[:, np.newaxis]
d2

array([[1],
       [2],
       [3],
       [4]])

## Array sorting

#### np.array.sort sorts in-place

In [ ]:
e1 = np.array([[4, 12, 8], [23, 9, 7], [12, 6, 15]])
e1

In [42]:
e1.sort(axis=0)
e1

array([[ 4,  6,  7],
       [12,  9,  8],
       [23, 12, 15]])

In [43]:
e1.sort(axis=1)
e1

array([[ 4,  6,  7],
       [ 8,  9, 12],
       [12, 15, 23]])

#### np.sort returns a new array

In [44]:
e2 = np.array([[8, 24, 19], [33, 12, 9], [25, 2, 14]])
e2

array([[ 8, 24, 19],
       [33, 12,  9],
       [25,  2, 14]])

In [45]:
np.sort(e2, axis=0)

array([[ 8,  2,  9],
       [25, 12, 14],
       [33, 24, 19]])

In [46]:
np.sort(e2, axis=1)

array([[ 8, 19, 24],
       [ 9, 12, 33],
       [ 2, 14, 25]])