In [13]:
import math
import numpy as np
np.random.seed(44)
ar = np.random.randint(0, 25, 10)
ar

array([20,  3, 17, 13,  3,  0, 20,  3, 15, 10])

In [5]:
maskedArr = (ar % 2 == 0)
maskedArr

array([ True, False, False, False, False,  True,  True, False, False,  True], dtype=bool)

In [6]:
ar1 = np.array([1, 2, 3, 4])
ar2 = np.array([2, 4, 6, 8])
(ar1 * ar2)

array([ 2,  8, 18, 32])

In [7]:
ar3 = np.array([1, 3, 5, 7])
(ar1 * ar2 - ar3)

array([ 1,  5, 13, 25])

In [8]:
(ar1 * ar2 - ar3) ^ 2

array([ 3,  7, 15, 27])

In [9]:
(ar1 * ar2 - ar3) ** 2

array([  1,  25, 169, 625])

In [10]:
ar[maskedArr]

array([20,  0, 20, 10])

In [11]:
ar

array([20,  3, 17, 13,  3,  0, 20,  3, 15, 10])

In [12]:
ar[[2,3,6,7]]

array([17, 13, 20,  3])

In [13]:
ar

array([20,  3, 17, 13,  3,  0, 20,  3, 15, 10])

In [14]:
ar.T

array([20,  3, 17, 13,  3,  0, 20,  3, 15, 10])

In [15]:
ar.transpose()

array([20,  3, 17, 13,  3,  0, 20,  3, 15, 10])

In [16]:
ar1 = np.array([1,2,3])
ar2 = np.array([[1],[2],[3]])
ar1 * ar2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [17]:
ar1.dot(ar2)

array([14])

In [18]:
ar1.T

array([1, 2, 3])

In [19]:
ar2.T

array([[1, 2, 3]])

In [20]:
ar1 = np.array([[1, 2, 3]])

In [21]:
ar1 * ar2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [22]:
ar1.dot(ar2)

array([[14]])

In [23]:
ar1.T

array([[1],
       [2],
       [3]])

In [24]:
ar2

array([[1],
       [2],
       [3]])

In [25]:
ar2.T

array([[1, 2, 3]])

In [26]:
ar1 = np.array([[1,2],[3,4],[5,6]])
ar1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
ar1.ravel()

array([1, 2, 3, 4, 5, 6])

In [28]:
ar1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
ar1.flatten()

array([1, 2, 3, 4, 5, 6])

In [30]:
ar2 = np.array([1,2,3,4,5,6,7,8])
ar2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
ar2.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
ar2.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
np.ones(4,)

array([ 1.,  1.,  1.,  1.])

In [34]:
np.ones(,4)

SyntaxError: invalid syntax (<ipython-input-34-0aec23d62925>, line 1)

In [35]:
np.ones(4,1)

TypeError: data type not understood

In [36]:
np.ones((4,1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [37]:
np.ones((1,4))

array([[ 1.,  1.,  1.,  1.]])

In [38]:
np.arange(5, axis=1)

TypeError: 'axis' is an invalid keyword argument for this function

In [39]:
ar1 = np.array([[1],[2],[3],[4]])
ar1

array([[1],
       [2],
       [3],
       [4]])

In [40]:
ar2 = np.ones((4,1))
ar2

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [41]:
np.concatenate(ar2, ar2)

TypeError: only length-1 arrays can be converted to Python scalars

In [42]:
np.concatenate((ar2, ar1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.]])

In [43]:
np.concatenate((ar2,ar1), axis=1)

array([[ 1.,  1.],
       [ 1.,  2.],
       [ 1.,  3.],
       [ 1.,  4.]])

In [3]:
a1 = np.array([1, 4, 9, 44, 23, 73, 29, 11])
a1

array([ 1,  4,  9, 44, 23, 73, 29, 11])

In [4]:
a1.mean()

24.25

In [17]:
a1.std() ** 2

518.6875

In [20]:
(a1 ** 2 - mean).sum() / a1.std() ** 2

16.695987468369683

In [8]:
mean = a1.sum() / a1.size
mean

24.25

In [16]:
math.sqrt((a1 ** 2 - mean).sum() / a1.size)

32.901367752724205