# Declaring Tensors

In [5]:
import tensorflow as tf
import numpy as np
NROWS = 3
NCOLS = 4

sess = tf.InteractiveSession()

### Fixed tensors

In [48]:
zeros = tf.zeros(shape=[NROWS, NCOLS], dtype=tf.int32, name='zeros')
print(zeros)
zeros.eval(session=sess)

Tensor("zeros_6:0", shape=(3, 4), dtype=int32)


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [47]:
ones = tf.ones(shape=[NROWS, NCOLS], dtype=tf.float32, name='ones')
print(ones)
ones.eval(session=sess)

Tensor("ones_3:0", shape=(3, 4), dtype=float32)


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]], dtype=float32)

In [46]:
filled = tf.fill(dims=[NROWS, NCOLS], value=0.5, name='filled')
print(filled)
filled.eval(session=sess)

Tensor("filled:0", shape=(3, 4), dtype=float32)


array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5]], dtype=float32)

In [45]:
consts1 = tf.constant(value=[[1, 1, 1], [2, 2, 2]], name='consts1')
print(consts1)
consts1.eval(session=sess)

Tensor("consts1:0", shape=(2, 3), dtype=int32)


array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)

In [44]:
const2 = tf.constant(shape=[NROWS, NCOLS], value=1.5, dtype=tf.float64, name='const2')
print(const2)
const2.eval(session=sess)

Tensor("const2:0", shape=(3, 4), dtype=float64)


array([[ 1.5,  1.5,  1.5,  1.5],
       [ 1.5,  1.5,  1.5,  1.5],
       [ 1.5,  1.5,  1.5,  1.5]])

### Tensors of similar shape

In [43]:
zeros_like = tf.zeros_like(tensor=consts1, dtype=tf.float16, optimize=False, name='zeros_like')
print(zeros_like)
zeros_like.eval(session=sess)

Tensor("zeros_like_4:0", shape=(2, 3), dtype=float16)


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float16)

In [42]:
ones_like = tf.ones_like(tensor=const2, dtype=tf.int64, optimize=True, name='ones_like')
print(ones_like)
ones_like.eval(session=sess)

Tensor("ones_like_1:0", shape=(3, 4), dtype=int64)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Sequence tensors

In [66]:
linear = tf.linspace(start=0.5, stop=1.8, num=15, name='linear')
print(linear)
linear.eval(session=sess)

Tensor("linear_2:0", shape=(15,), dtype=float32)


array([ 0.5       ,  0.59285712,  0.68571424,  0.77857143,  0.87142855,
        0.96428567,  1.05714285,  1.14999998,  1.2428571 ,  1.33571422,
        1.42857134,  1.52142847,  1.61428571,  1.70714283,  1.79999995], dtype=float32)

In [52]:
seq = tf.range(start=-1.5, limit=2, delta=0.3, name='seq')
print(seq)
seq.eval(session=sess)

Tensor("seq:0", shape=(12,), dtype=float32)


array([-1.5       , -1.20000005, -0.90000004, -0.60000002, -0.30000001,
        0.        ,  0.30000001,  0.60000002,  0.90000004,  1.20000005,
        1.5       ,  1.79999995], dtype=float32)

### Random tensors

In [58]:
randu = tf.random_uniform(shape=[NROWS, NCOLS], minval=-1.5, maxval=1.5, dtype=tf.float32, name='randu')
print(randu)
randu.eval(session=sess)

Tensor("randu_1:0", shape=(3, 4), dtype=float32)


array([[ 0.04379261, -1.23091149,  0.58356071, -0.34657288],
       [ 0.85153985, -0.18326783, -0.89315951,  1.14479446],
       [-0.14480531, -0.67774808,  0.56082129,  1.16890383]], dtype=float32)

In [55]:
randn = tf.random_normal(shape=[NROWS, NCOLS], mean=2.5, stddev=0.6, dtype=tf.float16, name='randn')
print(randn)
randn.eval(session=sess)

Tensor("randn_1:0", shape=(3, 4), dtype=float16)


array([[ 3.1796875 ,  3.328125  ,  2.10351562,  2.33789062],
       [ 2.45117188,  3.07421875,  2.44726562,  2.23242188],
       [ 2.65234375,  2.328125  ,  2.55859375,  2.54101562]], dtype=float16)

In [61]:
randnt = tf.truncated_normal(shape=[NROWS, NCOLS], mean=-1.2, stddev=0.4, dtype=tf.float64, name='randnt')
print(randnt)
randnt.eval(session=sess)

Tensor("randnt_1:0", shape=(3, 4), dtype=float64)


array([[-1.33049068, -1.14467178, -0.71711957, -1.07640052],
       [-1.71351627, -1.24732577, -1.3576249 , -0.88537022],
       [-1.25343132, -0.68211961, -1.01170417, -0.73458419]])

In [63]:
shuffle = tf.random_shuffle(value=seq, name='shuffle')
print(shuffle)
shuffle.eval(session=sess)

Tensor("shuffle:0", shape=(12,), dtype=float32)


array([ 1.79999995, -1.5       ,  1.5       , -0.60000002,  0.        ,
        0.30000001, -0.90000004,  0.60000002,  0.90000004,  1.20000005,
       -0.30000001, -1.20000005], dtype=float32)

In [68]:
crop = tf.random_crop(value=linear, size=[10], name='crop')
print(crop)
crop.eval(session=sess)

Tensor("crop_1:0", shape=(10,), dtype=float32)


array([ 0.96428567,  1.05714285,  1.14999998,  1.2428571 ,  1.33571422,
        1.42857134,  1.52142847,  1.61428571,  1.70714283,  1.79999995], dtype=float32)

### Convert to Tensor

In [72]:
array = np.identity(n=5, dtype=np.int32)
tensor = tf.convert_to_tensor(value=array, dtype=tf.int64, name='tensor')
print(tensor)
tensor.eval(session=sess)

Tensor("tensor:0", shape=(5, 5), dtype=int64)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])