# Using Placeholders and Variables 

In [2]:
import numpy as np
import tensorflow as tf

sess = tf.InteractiveSession()

### Variables

In [3]:
var1 = tf.Variable(initial_value=9, dtype=tf.int64, name='var1')
print(var1)
var2 = tf.Variable(initial_value=[[1, 2], [3, 4]], dtype=tf.float16, name='var2')
print(var2)

sess.run(tf.global_variables_initializer())
print(sess.run(var1))
print(sess.run(var2))

Tensor("var1/read:0", shape=(), dtype=int64)
Tensor("var2/read:0", shape=(2, 2), dtype=float16)
9
[[ 1.  2.]
 [ 3.  4.]]


In [15]:
var3 = tf.Variable([8, 7], dtype=tf.float32, name='var3')
print(var3)
var4 = tf.Variable(tf.pow(x=var3.initialized_value(), y=2), dtype=tf.float32, name='var4')
print(var4)

sess.run(tf.global_variables_initializer())
print(sess.run(var3))
print(sess.run(var4))

Tensor("var3_7/read:0", shape=(2,), dtype=float32)
Tensor("var4_4/read:0", shape=(2,), dtype=float32)
[ 8.  7.]
[ 64.  49.]


In [19]:
var5 = tf.Variable(tf.zeros(shape=[2, 3]), name='var5')
print(var5)
sess.run(var5.initializer)

var6 = tf.Variable(tf.ones_like(var5), name='var6')
print(var6)
sess.run(var6.initializer)

print(sess.run(var5))
print(sess.run(var6))

Tensor("var5_3/read:0", shape=(2, 3), dtype=float32)
Tensor("var6/read:0", shape=(2, 3), dtype=float32)
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


### Placeholders

In [22]:
plh = tf.placeholder(shape=[2, 3], dtype=tf.float32, name='plh')
print(plh)

res = tf.pow(x=plh, y=2, name='res')
print(res)

vals = np.array([[2, 5, 4], [1, 9, 3]])
sess.run(fetches=res, feed_dict={plh: vals})

Tensor("plh_2:0", shape=(2, 3), dtype=float32)
Tensor("res:0", shape=(2, 3), dtype=float32)


array([[  4.,  25.,  16.],
       [  1.,  81.,   9.]], dtype=float32)