# Working with Matrices

In [2]:
import numpy as np
import tensorflow as tf

sess = tf.InteractiveSession()

In [10]:
a = tf.constant(value=[[2, 3], [5, 5]], dtype=tf.int32)
b = tf.constant(value=[[1, 3], [2, 4]], dtype=tf.int32)
c = tf.constant(value=[[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=tf.float32)

### Matrix multiplication

In [24]:
sess.run(tf.matmul(a=a, b=b))

array([[  8.,  18.],
       [ 15.,  35.]], dtype=float32)

### Transpose

In [30]:
sess.run(tf.transpose(a=a))

array([[ 2.,  5.],
       [ 3.,  5.]], dtype=float32)

### Determinate and Inverse

In [31]:
sess.run(tf.matrix_determinant(input=b))

-2.0

In [32]:
sess.run(tf.matrix_inverse(input=a))

array([[-1.        ,  0.60000002],
       [ 1.        , -0.40000001]], dtype=float32)

### Decomposition

In [47]:
sess.run(tf.cholesky(input=c))

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]], dtype=float32)

### Eigenvalues and Eigenvector

In [50]:
sess.run(tf.self_adjoint_eigvals(tensor=c))

array([  1.88096873e-02,   1.55039663e+01,   1.23477234e+02], dtype=float32)

In [49]:
sess.run(tf.self_adjoint_eig(tensor=c))

(array([  1.88096873e-02,   1.55039663e+01,   1.23477234e+02], dtype=float32),
 array([[ 0.96341878,  0.21272728,  0.16300693],
        [-0.26483005,  0.84895217,  0.45732397],
        [ 0.04109978,  0.48376369, -0.87423301]], dtype=float32))