# Declaring Operations

In [2]:
import numpy as np
import tensorflow as tf

sess = tf.InteractiveSession()

In [46]:
a = tf.constant(value=[[2, 3], [2, 5]], dtype=tf.int32)
b = tf.constant(value=[[1, 3], [5, 4]], dtype=tf.int32)
c = tf.constant(value=[[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=tf.float32)
d = tf.constant(value=[[4.5, 2.6, 3.1], [7.1, 8.3, 1.2]])
e = tf.constant(value=[[1.8, 9.2, 3.5], [5.5, 1.2, 7.0]])

### Basic operations

In [47]:
sess.run(tf.add(x=a, y=b))
# sess.run(a + b)

array([[3, 6],
       [7, 9]], dtype=int32)

In [48]:
sess.run(tf.subtract(x=a, y=b))
# sess.run(a - b)

array([[ 1,  0],
       [-3,  1]], dtype=int32)

In [49]:
sess.run(tf.multiply(x=a, y=b))
# sess.run(a * b)

array([[ 2,  9],
       [10, 20]], dtype=int32)

In [50]:
sess.run(tf.div(x=a, y=b))
# sess.run(a // b)

array([[2, 1],
       [0, 1]], dtype=int32)

In [51]:
sess.run(tf.divide(x=a, y=b))
# sess.run(tf.truediv(x=a, y=b))
# sess.run(a / b)

array([[ 2.  ,  1.  ],
       [ 0.4 ,  1.25]])

In [52]:
sess.run(tf.floor_div(x=d, y=e))

array([[ 2.,  0.,  0.],
       [ 1.,  6.,  0.]], dtype=float32)

In [53]:
# sess.run(tf.mod(x=a, y=b))
sess.run(a % b)

array([[0, 0],
       [2, 1]], dtype=int32)

In [54]:
# sess.run(tf.pow(x=a, y=b))
sess.run(a ** b)

array([[  2,  27],
       [ 32, 625]], dtype=int32)

### Cross Product

In [55]:
sess.run(tf.cross(a=d, b=e))

array([[-19.41999817, -10.17000008,  36.71999741],
       [ 56.66000366, -43.09999847, -37.13000107]], dtype=float32)

### Other Mathematic Functions

In [56]:
sess.run(tf.abs(x=c))

array([[  4.,  12.,  16.],
       [ 12.,  37.,  43.],
       [ 16.,  43.,  98.]], dtype=float32)

In [57]:
sess.run(tf.ceil(x=d))

array([[ 5.,  3.,  4.],
       [ 8.,  9.,  2.]], dtype=float32)

In [58]:
sess.run(tf.cos(x=d))

array([[-0.21079579, -0.85688865, -0.99913514],
       [ 0.68454671, -0.43137702,  0.36235771]], dtype=float32)

In [59]:
sess.run(tf.exp(x=e))

array([[  6.04964733e+00,   9.89712695e+03,   3.31154518e+01],
       [  2.44691925e+02,   3.32011700e+00,   1.09663318e+03]], dtype=float32)

In [60]:
sess.run(tf.floor(x=d))

array([[ 4.,  2.,  3.],
       [ 7.,  8.,  1.]], dtype=float32)

In [61]:
sess.run(tf.log(x=e))

array([[ 0.58778661,  2.21920347,  1.25276303],
       [ 1.70474815,  0.18232159,  1.9459101 ]], dtype=float32)

In [62]:
sess.run(tf.maximum(x=a, y=b))

array([[2, 3],
       [5, 5]], dtype=int32)

In [63]:
sess.run(tf.minimum(x=d, y=e))

array([[ 1.79999995,  2.5999999 ,  3.0999999 ],
       [ 5.5       ,  1.20000005,  1.20000005]], dtype=float32)

In [64]:
sess.run(tf.negative(x=c))

array([[ -4., -12.,  16.],
       [-12., -37.,  43.],
       [ 16.,  43., -98.]], dtype=float32)

In [65]:
sess.run(tf.pow(x=a, y=b))

array([[  2,  27],
       [ 32, 625]], dtype=int32)

In [66]:
sess.run(tf.round(x=d))

array([[ 4.,  3.,  3.],
       [ 7.,  8.,  1.]], dtype=float32)

In [68]:
sess.run(tf.rsqrt(x=e))

array([[ 0.74535596,  0.32969025,  0.53452247],
       [ 0.42640141,  0.91287088,  0.3779645 ]], dtype=float32)

In [69]:
sess.run(tf.sign(x=c))

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.]], dtype=float32)

In [70]:
sess.run(tf.sin(x=e))

array([[ 0.97384763,  0.22289009, -0.35078323],
       [-0.7055403 ,  0.93203908,  0.65698659]], dtype=float32)

In [72]:
sess.run(tf.sqrt(x=d))

array([[ 2.12132025,  1.61245155,  1.76068151],
       [ 2.66458249,  2.88097215,  1.09544516]], dtype=float32)

In [74]:
sess.run(tf.square(x=c))

array([[   16.,   144.,   256.],
       [  144.,  1369.,  1849.],
       [  256.,  1849.,  9604.]], dtype=float32)

### Specialty Mathematic Functions

In [77]:
sess.run(tf.digamma(x=c))

array([[ 1.2561177 ,  2.44266152,         inf],
       [ 2.44266152,  3.59734344,         inf],
       [        inf,         inf,  4.57985687]], dtype=float32)

In [78]:
sess.run(tf.erf(x=d))

array([[ 1.        ,  0.99976397,  0.99998838],
       [ 1.        ,  1.        ,  0.91031396]], dtype=float32)

In [79]:
sess.run(tf.erfc(x=e))

array([[  1.09095005e-02,   1.06273537e-38,   7.43098383e-07],
       [  7.35784826e-15,   8.96860063e-02,   4.18382573e-23]], dtype=float32)

In [82]:
sess.run(tf.igamma(a=d, x=e))

array([[  6.42835721e-02,   9.97082710e-01,   6.57908320e-01],
       [  2.99913555e-01,   2.03461022e-05,   9.98496354e-01]], dtype=float32)

In [83]:
sess.run(tf.igammac(a=e, x=d))

array([[  4.65375558e-02,   9.98862147e-01,   5.16600311e-01],
       [  2.22123608e-01,   4.22441895e-04,   9.99748886e-01]], dtype=float32)

In [87]:
sess.run(tf.lbeta(x=d))

array([ -9.6557436 , -13.73765469], dtype=float32)

In [88]:
sess.run(tf.lgamma(x=e))

array([[ -0.07108389,  11.03506279,   1.20097363],
       [  3.95781398,  -0.0853741 ,   6.57925129]], dtype=float32)

In [89]:
sess.run(tf.squared_difference(x=a, y=b))

array([[1, 0],
       [9, 1]], dtype=int32)